package com.midstane.lighthouse.repository.processor.crud

class ExposedCrudRepositoryRenderer {
    fun render(model: CrudRepositoryModel): String = buildString {
        //appendLine("@file:Suppress(\"DEPRECATION\", \"DEPRECATION_ERROR\")")
        appendLine()
        appendLine("package ${model.packageName}")
        appendLine()
        appendLine("import ${model.bindingScope.qualifiedName}")
        appendLine("import ${model.entity.qualifiedName}")
        appendLine("import dev.zacsweers.metro.ContributesBinding")
        appendLine("import dev.zacsweers.metro.Inject")
        appendLine("import dev.zacsweers.metro.binding")
        appendLine("import kotlinx.coroutines.flow.map")
        appendLine("import kotlinx.coroutines.flow.singleOrNull")
        appendLine("import kotlinx.coroutines.flow.toList")
        appendLine("import org.jetbrains.exposed.v1.core.dao.id.LongIdTable")
        appendLine("import org.jetbrains.exposed.v1.core.ResultRow")
        appendLine("import org.jetbrains.exposed.v1.datetime.CurrentTimestamp")
        appendLine("import org.jetbrains.exposed.v1.datetime.timestamp")
        appendLine("import org.jetbrains.exposed.v1.core.eq")
        appendLine("import org.jetbrains.exposed.v1.core.StdOutSqlLogger")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.R2dbcDatabase")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.SchemaUtils")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.deleteWhere")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.insert")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.insertAndGetId")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.selectAll")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.transactions.suspendTransaction")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.update")
        appendLine("import java.time.OffsetDateTime")
        appendLine("import kotlin.time.Clock")
        appendLine()
        appendLine("@ContributesBinding(${model.bindingScope.simpleName}::class, binding<${model.repositoryName}>())")
        appendLine("@Inject")
        appendLine("class ${model.generatedName}(")
        appendLine("    private val database: R2dbcDatabase,")
        appendLine(") : ${model.repositoryName} {")
        appendLine()
        appendSave(model)
        appendLine()
        appendFindById(model)
        appendLine()
        appendFindAll(model)
        appendLine()
        appendDeleteById(model)
        model.finders.forEach { finder ->
            appendLine()
            appendFinder(model, finder)
        }
        appendLine()
        appendTransaction(model)
        appendLine()
        appendMapper(model)
        appendLine()
        appendTable(model)
        appendLine("}")
    }

    private fun StringBuilder.appendSave(model: CrudRepositoryModel) {
        val autogeneratedProperties = model.uniqueProperties()
        appendLine("    override suspend fun save(entity: ${model.entity.simpleName}): ${model.entity.simpleName} = transaction {")
        appendLine("        var insertedEntity = entity")
        appendLine("        val updatedRows = ${model.tableObjectName}.update({ ${model.tableObjectName}.${model.idProperty.name} eq entity.${model.idProperty.name} }) {")
        model.properties.filter { it.shouldAssign() && !it.options.unique }.forEach { property ->
            appendLine("            it[${model.tableObjectName}.${property.name}] = entity.${property.name}")
        }
        appendLine("                it[${model.tableObjectName}.updatedAt] = Clock.System.now()")
        appendLine("        }")
        appendLine()
        appendLine("        if (updatedRows == 0) {")
        appendInsertBranch(model, autogeneratedProperties)
        appendLine("        }")
        appendLine("        insertedEntity")
        appendLine("    }")
    }

    private fun StringBuilder.appendInsertBranch(model: CrudRepositoryModel, autogeneratedProperties: List<EntityProperty>) {
        appendLine("            val id = ${model.tableObjectName}.insertAndGetId {")
        model.properties.filter { it.shouldAssign() }.forEach { property ->
            appendLine("                it[${model.tableObjectName}.${property.name}] = entity.${property.name}")
        }
        appendLine("            }")
        appendLine("            insertedEntity = insertedEntity.copy(id = id.value)")
    }

    private fun StringBuilder.appendFindById(model: CrudRepositoryModel) {
        appendLine("    override suspend fun findById(id: ${model.idProperty.type.qualifiedName}): ${model.entity.simpleName}? = transaction {")
        appendLine("        ${model.tableObjectName}.selectAll()")
        appendLine("            .where { ${model.tableObjectName}.${model.idProperty.name} eq id }")
        appendLine("            .singleOrNull()")
        appendLine("            ?.let(::toEntity)")
        appendLine("    }")
    }

    private fun StringBuilder.appendFindAll(model: CrudRepositoryModel) {
        appendLine("    override suspend fun findAll(): List<${model.entity.simpleName}> = transaction {")
        appendLine("        ${model.tableObjectName}.selectAll().map(::toEntity).toList()")
        appendLine("    }")
    }

    private fun StringBuilder.appendDeleteById(model: CrudRepositoryModel) {
        appendLine("    override suspend fun deleteById(id: ${model.idProperty.type.qualifiedName}) {")
        appendLine("        transaction {")
        appendLine("            ${model.tableObjectName}.deleteWhere { ${model.tableObjectName}.${model.idProperty.name} eq id }")
        appendLine("        }")
        appendLine("    }")
    }

    private fun StringBuilder.appendFinder(model: CrudRepositoryModel, finder: Finder) {
        appendLine("    override suspend fun ${finder.functionName}(${finder.parameterName}: ${finder.property.type.qualifiedName}): ${model.entity.simpleName}? = transaction {")
        appendLine("        ${model.tableObjectName}.selectAll()")
        appendLine("            .where { ${model.tableObjectName}.${finder.property.name} eq ${finder.parameterName} }")
        appendLine("            .singleOrNull()")
        appendLine("            ?.let(::toEntity)")
        appendLine("    }")
    }

    private fun StringBuilder.appendTransaction(model: CrudRepositoryModel) {
        appendLine("    private suspend fun <T> transaction(block: suspend () -> T): T {")
        appendLine("        return suspendTransaction(database) {")
        appendLine("            addLogger(StdOutSqlLogger)")
        appendLine("            SchemaUtils.createMissingTablesAndColumns(${model.tableObjectName})")
        appendLine("            block()")
        appendLine("        }")
        appendLine("    }")
    }

    private fun StringBuilder.appendMapper(model: CrudRepositoryModel) {
        appendLine("    private fun toEntity(row: ResultRow): ${model.entity.simpleName} {")
        appendLine("        return ${model.entity.simpleName}(")
        model.properties.forEach { property ->
            if (property.column == ExposedColumn.Long && property.name == model.idProperty.name) {
                appendLine("            ${property.name} = ${property.rowAccess(model)}.value,")
            }else {
                appendLine("            ${property.name} = ${property.rowAccess(model)},")
            }
        }
        appendLine("        )")
        appendLine("    }")
    }

    private fun StringBuilder.appendTable(model: CrudRepositoryModel) {
        appendLine("    private object ${model.tableObjectName} : LongIdTable(${model.tableName.quote()}) {")
        model.properties.filter { it.generateColumn }.forEach { property ->
            appendLine("        val ${property.name} = ${property.column.render(property)}")
        }
        appendLine("        val createdAt = timestamp(\"created_at\").defaultExpression(CurrentTimestamp)")
        appendLine("        val updatedAt = timestamp(\"updated_at\").defaultExpression(CurrentTimestamp)")
        if (!model.primaryKeyIsInherited) {
            appendLine()
            appendLine("        override val primaryKey = PrimaryKey(${model.idProperty.name})")
        }
        appendLine("    }")
    }

    private fun EntityProperty.shouldAssign(): Boolean {
        return generateColumn && !options.autogenerate
    }

    private fun CrudRepositoryModel.uniqueProperties(): List<EntityProperty> {
        return properties.filter { property -> property.options.unique }
    }

    private fun EntityProperty.rowAccess(model: CrudRepositoryModel): String {
        return "row[${model.tableObjectName}.${name}]"
    }

    private fun ExposedColumn.render(property: EntityProperty): String {
        val name = property.name.quote()
        val column = when (this) {
            ExposedColumn.Boolean -> "bool($name)"
            ExposedColumn.Int -> "integer($name)"
            ExposedColumn.Long -> "long($name)"
            ExposedColumn.String -> "varchar($name, 255)"
            ExposedColumn.Text -> "text($name)"
            ExposedColumn.Uuid -> "uuid($name)"
            is ExposedColumn.Enum -> "enumerationByName<${type.qualifiedName}>($name, 255)"
        }

        return buildString {
            append(column)
            if (property.options.unique) append(".uniqueIndex()")
            if (property.options.autogenerate) {
                when (property.column) {
                    ExposedColumn.Uuid -> append(".autoGenerate()")
                    else -> append(".autoIncrement()")
                }
            }
            property.options.defaultValue?.let { append(".default($it)") }
        }
    }

    private fun String.quote(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
