ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.midstane.lighthouse.ApplicationKt.init
    ]
  }
}

database {
  r2dbc {
    url = "r2dbc:postgresql://localhost:5432/lighthouse"
    url = ${?DATABASE_R2DBC_URL}
    driver = "postgresql"
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "password"
    password = ${?DATABASE_PASSWORD}
  }
}

smtp {
  host = "localhost"
  host = ${?SMTP_HOST}
  port = 587
  port = ${?SMTP_PORT}
  username = ""
  username = ${?SMTP_USERNAME}
  password = ""
  password = ${?SMTP_PASSWORD}
  startTls = true
  startTls = ${?SMTP_STARTTLS}
  ssl = false
  ssl = ${?SMTP_SSL}
  timeoutMillis = 10000
  timeoutMillis = ${?SMTP_TIMEOUT_MILLIS}
}
