package com.midstane.lighthouse.repository.annotations

import kotlin.reflect.KClass

/**
 * Marks an interface as a mapper whose implementation is generated by Lighthouse's KSP processor.
 *
 * Mapper functions create the return type by calling its primary constructor. Constructor parameters
 * are filled from source parameters by matching properties with the same name and type. When a mapper
 * function has multiple source parameters and a target property could come from more than one source,
 * add [Mapping] to make the source explicit.
 *
 * Example:
 * ```kotlin
 * @Mapper(bindingScope = LightHouseScope::class)
 * interface UserMapper {
 *     fun toUser(dto: UserDto): User
 *
 *     @Mapping(target = "id", source = "user.id")
 *     @Mapping(target = "uuid", expression = "user.uuid.toString()")
 *     @Mapping(target = "occupationType", source = "occupation.type")
 *     fun toDto(user: User, occupation: Occupation): UserDto
 * }
 * ```
 *
 * The generated class is named `Generated<InterfaceName>` unless [generatedName] is set. It is
 * contributed to Metro using [bindingScope], so it can be injected by the mapper interface type.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class Mapper(
    val bindingScope: KClass<*>,
    val generatedName: String = "",
)

/**
 * Overrides how one target constructor parameter is populated in a generated mapper function.
 *
 * Set exactly one of [source] or [expression]:
 *
 * - [source] points to a source parameter or property path. For example, `source = "dto.email"`,
 *   `source = "occupation.type"`, or `source = "userId"` for a scalar source parameter.
 * - [expression] is copied directly into the generated constructor call. Use it for constants or
 *   conversions, such as `expression = "0L"` or `expression = "user.uuid.toString()"`.
 *
 * Example:
 * ```kotlin
 * @Mapping(target = "id", expression = "0L")
 * @Mapping(target = "type", source = "dto.occupationType")
 * fun toOccupation(dto: UserDto, userId: Long): Occupation
 * ```
 */
@Repeatable
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.SOURCE)
annotation class Mapping(
    val target: String,
    val source: String = "",
    val expression: String = "",
)

/**
 * Container annotation for repeated [Mapping] declarations.
 *
 * Kotlin callers normally use repeated `@Mapping` annotations directly. This type exists so the
 * repeatable annotation can also be represented as a single annotation value when needed.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.SOURCE)
annotation class Mappings(
    val value: Array<Mapping>,
)