package com.midstane.lighthouse.repository.processor.crud

class ExposedCrudRepositoryRenderer {
    fun renderRepository(model: CrudRepositoryModel): String = buildString {
        appendLine("package ${model.packageName}")
        appendLine()
        appendLine("import ${model.bindingScope.qualifiedName}")
        appendLine("import ${model.entity.qualifiedName}")
        appendLine("import ${model.tablePackageName}.${model.tableObjectName}")
        appendLine("import dev.zacsweers.metro.ContributesBinding")
        appendLine("import dev.zacsweers.metro.Inject")
        appendLine("import dev.zacsweers.metro.binding")
        appendLine("import kotlinx.coroutines.flow.map")
        appendLine("import kotlinx.coroutines.flow.singleOrNull")
        appendLine("import kotlinx.coroutines.flow.toList")
        appendLine("import org.jetbrains.exposed.v1.core.ResultRow")
        appendLine("import org.jetbrains.exposed.v1.core.eq")
        appendLine("import org.jetbrains.exposed.v1.core.StdOutSqlLogger")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.R2dbcDatabase")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.SchemaUtils")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.deleteWhere")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.insert")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.insertReturning")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.selectAll")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.transactions.suspendTransaction")
        appendLine("import org.jetbrains.exposed.v1.r2dbc.updateReturning")
        appendLine("import kotlin.time.Clock")
        appendLine()
        appendLine("@ContributesBinding(${model.bindingScope.simpleName}::class, binding<${model.repositoryName}>())")
        appendLine("@Inject")
        appendLine("class ${model.generatedName}(")
        appendLine("    private val database: R2dbcDatabase,")
        appendLine(") : ${model.repositoryName} {")
        appendLine()
        appendSave(model)
        appendLine()
        appendFindById(model)
        appendLine()
        appendFindAll(model)
        appendLine()
        appendDeleteById(model)
        model.finders.forEach { finder ->
            appendLine()
            appendFinder(model, finder)
        }
        appendLine()
        appendTransaction(model)
        appendLine()
        appendMapper(model)
        appendLine()
        appendLine("}")
    }

    fun renderTable(model: CrudRepositoryModel): String = buildString {
        if (model.properties.any { it.column == ExposedColumn.Uuid }) {
            appendLine("@file:OptIn(ExperimentalUuidApi::class)")
            appendLine()
        }
        appendLine("package ${model.tablePackageName}")
        appendLine()
        model.properties.mapNotNull { property -> property.enumType() }
            .distinctBy { type -> type.qualifiedName }
            .forEach { type -> appendLine("import ${type.qualifiedName}") }
        appendLine("import org.jetbrains.exposed.v1.core.dao.id.LongIdTable")
        appendLine("import org.jetbrains.exposed.v1.datetime.CurrentTimestamp")
        appendLine("import org.jetbrains.exposed.v1.datetime.date")
        appendLine("import org.jetbrains.exposed.v1.datetime.timestamp")
        if (model.properties.any { it.column == ExposedColumn.Uuid }) {
            appendLine("import kotlin.uuid.ExperimentalUuidApi")
        }
        appendLine()
        appendTable(model)
    }

    private fun StringBuilder.appendSave(model: CrudRepositoryModel) {
        val autogeneratedProperties = model.uniqueProperties()
        appendLine("    override suspend fun save(entity: ${model.entity.simpleName}): ${model.entity.simpleName} = transaction {")
        appendLine("        val updatedRows = ${model.tableObjectName}.updateReturning( where = { ${model.tableObjectName}.${model.idProperty.name} eq entity.${model.idProperty.name} }) {")
        model.properties.filter { it.shouldAssignOnUpdate() && !it.options.unique }.forEach { property ->
            appendLine("            it[${model.tableObjectName}.${property.name}] = entity.${property.name}")
        }
        appendLine("                it[${model.tableObjectName}.updatedAt] = Clock.System.now()")
        appendLine("        }.singleOrNull()")
        appendLine()
        appendLine("        if (updatedRows == null) {")
        appendInsertBranch(model, autogeneratedProperties)
        appendLine("        }")
        appendLine("        toEntity(updatedRows)")
        appendLine("    }")
    }

    private fun StringBuilder.appendInsertBranch(model: CrudRepositoryModel, autogeneratedProperties: List<EntityProperty>) {
        appendLine("            val data = ${model.tableObjectName}.insertReturning {")
        model.properties.filter { it.shouldAssignOnCreate() }.forEach { property ->
            appendLine("                it[${model.tableObjectName}.${property.name}] = entity.${property.name}")
        }
        appendLine("            }")
        appendLine("            return@transaction data.singleOrNull()?.let { toEntity(it) } ?: entity")
    }

    private fun StringBuilder.appendFindById(model: CrudRepositoryModel) {
        appendLine("    override suspend fun findById(id: ${model.idProperty.type.qualifiedName}): ${model.entity.simpleName}? = transaction {")
        appendLine("        ${model.tableObjectName}.selectAll()")
        appendLine("            .where { ${model.tableObjectName}.${model.idProperty.name} eq id }")
        appendLine("            .singleOrNull()")
        appendLine("            ?.let(::toEntity)")
        appendLine("    }")
    }

    private fun StringBuilder.appendFindAll(model: CrudRepositoryModel) {
        appendLine("    override suspend fun findAll(): List<${model.entity.simpleName}> = transaction {")
        appendLine("        ${model.tableObjectName}.selectAll().map(::toEntity).toList()")
        appendLine("    }")
    }

    private fun StringBuilder.appendDeleteById(model: CrudRepositoryModel) {
        appendLine("    override suspend fun deleteById(id: ${model.idProperty.type.qualifiedName}) {")
        appendLine("        transaction {")
        appendLine("            ${model.tableObjectName}.deleteWhere { ${model.tableObjectName}.${model.idProperty.name} eq id }")
        appendLine("        }")
        appendLine("    }")
    }

    private fun StringBuilder.appendFinder(model: CrudRepositoryModel, finder: Finder) {
        appendLine("    override suspend fun ${finder.functionName}(${finder.parameterName}: ${finder.property.type.qualifiedName}): ${finder.returnType(model)} = transaction {")
        appendLine("        ${model.tableObjectName}.selectAll()")
        appendLine("            .where { ${model.tableObjectName}.${finder.property.name} eq ${finder.parameterName} }")
        when (finder.kind) {
            DerivedQueryKind.FindOne -> {
                appendLine("            .singleOrNull()")
                appendLine("            ?.let(::toEntity)")
            }
            DerivedQueryKind.FindAll -> {
                appendLine("            .map(::toEntity)")
                appendLine("            .toList()")
            }
            DerivedQueryKind.Exists -> {
                appendLine("            .toList()")
                appendLine("            .isNotEmpty()")
            }
            DerivedQueryKind.Count -> {
                appendLine("            .toList()")
                appendLine("            .size")
                appendLine("            .toLong()")
            }
        }
        appendLine("    }")
    }

    private fun Finder.returnType(model: CrudRepositoryModel): String {
        return when (kind) {
            DerivedQueryKind.FindOne -> "${model.entity.simpleName}?"
            DerivedQueryKind.FindAll -> "List<${model.entity.simpleName}>"
            DerivedQueryKind.Exists -> "kotlin.Boolean"
            DerivedQueryKind.Count -> "kotlin.Long"
        }
    }

    private fun StringBuilder.appendTransaction(model: CrudRepositoryModel) {
        appendLine("    private suspend fun <T> transaction(block: suspend () -> T): T {")
        appendLine("        return suspendTransaction(database) {")
        appendLine("            addLogger(StdOutSqlLogger)")
        //appendLine("            SchemaUtils.createMissingTablesAndColumns(${model.tableObjectName})")
        appendLine("            block()")
        appendLine("        }")
        appendLine("    }")
    }

    private fun StringBuilder.appendMapper(model: CrudRepositoryModel) {
        appendLine("    private fun toEntity(row: ResultRow): ${model.entity.simpleName} {")
        appendLine("        return ${model.entity.simpleName}(")
        model.properties.forEach { property ->
            if (property.column == ExposedColumn.Long && property.name == model.idProperty.name) {
                appendLine("            ${property.name} = ${property.rowAccess(model)}.value,")
            }else {
                appendLine("            ${property.name} = ${property.rowAccess(model)},")
            }
        }
        appendLine("        )")
        appendLine("    }")
    }

    private fun StringBuilder.appendTable(model: CrudRepositoryModel) {
        appendLine("internal object ${model.tableObjectName} : LongIdTable(${model.tableName.quote()}) {")
        model.properties.filter { it.generateColumn }.forEach { property ->
            appendLine("    val ${property.name} = ${property.column.render(property)}")
        }
        if (model.properties.none { it.name == "createdAt" }) {
            appendLine("    val createdAt = timestamp(\"created_at\").defaultExpression(CurrentTimestamp)")
        }
        if (model.properties.none { it.name == "updatedAt" }) {
            appendLine("    val updatedAt = timestamp(\"updated_at\").defaultExpression(CurrentTimestamp)")
        }
        appendLine("}")
    }

    private fun EntityProperty.shouldAssign(): Boolean {
        return generateColumn && !options.autogenerate
    }

    private fun EntityProperty.shouldAssignOnCreate(): Boolean {
        return shouldAssign() && !isAutomaticTimestamp()
    }

    private fun EntityProperty.shouldAssignOnUpdate(): Boolean {
        return shouldAssign() && !isAutomaticTimestamp()
    }

    private fun EntityProperty.isAutomaticTimestamp(): Boolean {
        return column == ExposedColumn.Timestamp && (name == "createdAt" || name == "updatedAt")
    }

    private fun CrudRepositoryModel.uniqueProperties(): List<EntityProperty> {
        return properties.filter { property -> property.options.unique }
    }

    private fun EntityProperty.rowAccess(model: CrudRepositoryModel): String {
        val access = "row[${model.tableObjectName}.${name}]"
        return if (isAutomaticTimestamp() && type.qualifiedName == "kotlin.String") {
            "$access.toString()"
        } else {
            access
        }
    }

    private fun ExposedColumn.render(property: EntityProperty): String {
        val name = property.name.quote()
        val column = when (this) {
            ExposedColumn.Boolean -> "bool($name)"
            ExposedColumn.Int -> "integer($name)"
            ExposedColumn.Long -> "long($name)"
            ExposedColumn.String -> "varchar($name, 255)"
            ExposedColumn.Text -> "text($name)"
            ExposedColumn.Timestamp -> "timestamp(${property.timestampColumnName().quote()})"
            ExposedColumn.Date -> "date($name)"
            ExposedColumn.Uuid -> "uuid($name)"
            is ExposedColumn.Enum -> "enumerationByName<${type.qualifiedName}>($name, 255)"
        }

        return buildString {
            append(column)
            if (property.type.nullable) append(".nullable()")
            if (property.options.unique) append(".uniqueIndex()")
            if (property.options.autogenerate) {
                when (property.column) {
                    ExposedColumn.Uuid -> append(".autoGenerate()")
                    else -> append(".autoIncrement()")
                }
            }
            when {
                property.isAutomaticTimestamp() -> append(".defaultExpression(CurrentTimestamp)")
                property.options.defaultValue != null && !property.options.autogenerate -> append(".default(${property.options.defaultValue})")
            }
        }
    }

    private fun EntityProperty.enumType(): KotlinType? {
        return (column as? ExposedColumn.Enum)?.type
    }

    private fun EntityProperty.timestampColumnName(): String {
        return when (name) {
            "createdAt" -> "created_at"
            "updatedAt" -> "updated_at"
            else -> name
        }
    }

    private fun String.quote(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
